version: "3.9"
name: iot-studio-v1-container

services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb-1
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=iotstudio
      - TZ=Asia/Kolkata
    networks:
      - app_network
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://admin:iotstudio@localhost:5984/"]
      interval: 10s
      timeout: 5s
      retries: 5

  main-node-app:
    build:
      context: ./IoT-Studio
      dockerfile: Dockerfile
    container_name: iot-studio-app
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./IoT-Studio:/app
    command: ["python", "main.py"]
    ports:
      - "5000:5000"
    env_file:
      - ./IoT-Studio/.env

  worker-node-app:
    build:
      context: ./IoT-Studio-Worker
      dockerfile: Dockerfile
    container_name: iot-studio-app-worker
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./IoT-Studio-Worker:/app
    command: ["python", "main.py"]
    ports:
      - "4342:4342"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "2g"
    environment:
      - THREAD_COUNT=4
      - TZ=Asia/Kolkata

  mqtt-data-producer:
    image: mqtt-data-producer
    container_name: mqtt-data-producer
    networks:
      - app_network
    environment:
      - TZ=Asia/Kolkata
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  couchdb_data:
