version: "3.9"
name: iot-studio-v1-container

services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb-1
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=iotstudio
      - TZ=Asia/Kolkata
    networks:
      - app_network
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://admin:iotstudio@localhost:5984/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis1
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]

  main-node-app:
    build:
      context: ./IoT-Studio
      dockerfile: Dockerfile
    container_name: iot-studio-app
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - app_network
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./IoT-Studio:/app
    command: [ "python", "main.py" ]
    ports:
      - "5000:5000"
    env_file:
      - ./IoT-Studio/.env

  worker-node-app:
    build:
      context: ./IoT-Studio-Worker
      dockerfile: Dockerfile
    container_name: iot-studio-app-worker
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./IoT-Studio-Worker:/app
    command: [ "python", "main.py" ]
    ports:
      - "4342:4342"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "2g"
    environment:
      - THREAD_COUNT=4
      - TZ=Asia/Kolkata

  mqtt-data-producer:
    image: pandusa2003/mqtt-producer
    container_name: mqtt-producer
    networks:
      - app_network
    environment:
      - TZ=Asia/Kolkata
    restart: always

  grpc-server:
    build:
      context: ./IoT-Studio-worker-GRPC
      dockerfile: dockerfile
    container_name: grpc_server
    networks:
      - app_network
    ports:
      - "50051:50051"
    environment:
      - TZ=Asia/Kolkata

  grpc-client:
    build:
      context: ./RPCCLIENT
      dockerfile: dockerfile
    container_name: grpc_client
    networks:
      - app_network
    depends_on:
      - grpc-server
    environment:
      - GRPC_SERVER_HOST=nervous_driscoll
      - GRPC_SERVER_PORT=50051
    command: [ "python", "client.py" ]

  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    user: "1000:1000"  # Use your host user's UID:GID
    restart: always
    networks:
      - app_network 

networks:
  app_network:
    driver: bridge

volumes:
  couchdb_data:
    driver: local
  redis_data:
    driver: local
