# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iot_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'iot_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11iot_service.proto\x12\x03iot\"\xaf\x01\n\x11\x43onnectionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ntrigger_id\x18\x02 \x01(\t\x12\x15\n\rconnection_id\x18\x03 \x01(\t\x12\x16\n\x0e\x63onnection_url\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\x12\x0b\n\x03qos\x18\x06 \x01(\x05\x12\x12\n\nkeep_alive\x18\x07 \x01(\x05\x12\x17\n\x0fsubscribe_topic\x18\x08 \x01(\t\"$\n\x12\x43onnectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"S\n\x15StopConnectionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ntrigger_id\x18\x02 \x01(\t\x12\x15\n\rconnection_id\x18\x03 \x01(\t\"S\n\x16StopConnectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0e\x66ile_available\x18\x02 \x01(\x08\x12\x11\n\tfile_data\x18\x03 \x01(\x0c\"l\n\x17\x43onnectionStatusRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ntrigger_id\x18\x02 \x01(\t\x12\x1a\n\rconnection_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_connection_id\"F\n\x18\x43onnectionStatusResponse\x12*\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x15.iot.ConnectionRecord\"I\n\x10\x43onnectionRecord\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x02 \x01(\t\x12\x11\n\tclosed_at\x18\x03 \x01(\t\"Q\n\x13\x46ileDownloadRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ntrigger_id\x18\x02 \x01(\t\x12\x15\n\rconnection_id\x18\x03 \x01(\t\"A\n\x14\x46ileDownloadResponse\x12\x16\n\x0e\x66ile_available\x18\x01 \x01(\x08\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\x32\xb9\x02\n\nIoTService\x12\x42\n\x0fStartConnection\x12\x16.iot.ConnectionRequest\x1a\x17.iot.ConnectionResponse\x12I\n\x0eStopConnection\x12\x1a.iot.StopConnectionRequest\x1a\x1b.iot.StopConnectionResponse\x12R\n\x13GetConnectionStatus\x12\x1c.iot.ConnectionStatusRequest\x1a\x1d.iot.ConnectionStatusResponse\x12H\n\x11\x44ownloadExcelFile\x12\x18.iot.FileDownloadRequest\x1a\x19.iot.FileDownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTIONREQUEST']._serialized_start=27
  _globals['_CONNECTIONREQUEST']._serialized_end=202
  _globals['_CONNECTIONRESPONSE']._serialized_start=204
  _globals['_CONNECTIONRESPONSE']._serialized_end=240
  _globals['_STOPCONNECTIONREQUEST']._serialized_start=242
  _globals['_STOPCONNECTIONREQUEST']._serialized_end=325
  _globals['_STOPCONNECTIONRESPONSE']._serialized_start=327
  _globals['_STOPCONNECTIONRESPONSE']._serialized_end=410
  _globals['_CONNECTIONSTATUSREQUEST']._serialized_start=412
  _globals['_CONNECTIONSTATUSREQUEST']._serialized_end=520
  _globals['_CONNECTIONSTATUSRESPONSE']._serialized_start=522
  _globals['_CONNECTIONSTATUSRESPONSE']._serialized_end=592
  _globals['_CONNECTIONRECORD']._serialized_start=594
  _globals['_CONNECTIONRECORD']._serialized_end=667
  _globals['_FILEDOWNLOADREQUEST']._serialized_start=669
  _globals['_FILEDOWNLOADREQUEST']._serialized_end=750
  _globals['_FILEDOWNLOADRESPONSE']._serialized_start=752
  _globals['_FILEDOWNLOADRESPONSE']._serialized_end=817
  _globals['_IOTSERVICE']._serialized_start=820
  _globals['_IOTSERVICE']._serialized_end=1133
# @@protoc_insertion_point(module_scope)
