# Use the official Python image as the base
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

COPY  . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Run the gRPC client when the container starts
CMD ["python", "client.py"]
